[settings]
experimental = true

[tools]
usage = "latest"
node = "22.17.0"
awscli = "2.22.0"
neovim = "0.11.4"
"github:844196/wk" = "v1.0.2"

[env]
_.path = [
  # mise activate で登録されるフックの後に PATH の最上位をaquaにすることで
  # aquaとmiseを同時に使えるようにする
  # https://aquaproj.github.io/docs/reference/use-aqua-with-other-tools
  # https://zenn.dev/link/comments/4a06cbe069df4a
  "{{env.HOME}}/.local/share/aquaproj-aqua/bin"
]
